# Generated by Django 2.1 on 2018-08-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True, verbose_name='Название')),
                ('address', models.CharField(default=None, max_length=200, null=True, verbose_name='Адресс')),
                ('cinema_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True, verbose_name='Название')),
                ('about', models.CharField(default=None, max_length=1000, null=True, verbose_name='Описание')),
                ('poster_url', models.URLField(default=None, null=True, verbose_name='Постер')),
                ('movie_id', models.IntegerField(default=0, verbose_name='ID')),
                ('trailer_url', models.URLField(default=None, null=True, verbose_name='Трейлер')),
                ('genres', models.CharField(default=None, max_length=1000, null=True, verbose_name='Жанры')),
                ('runtime', models.IntegerField(default=None, null=True, verbose_name='Продолжительность')),
                ('rating', models.CharField(max_length=50, null=True, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=None, null=True, verbose_name='Время')),
                ('date', models.DateField(default=None, null=True, verbose_name='Дата')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='afisha.Cinema', verbose_name='Кинотеатр')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='afisha.Film', verbose_name='Фильм')),
            ],
        ),
    ]
